### ISSUE TITLE
Add support for attention models to MusicRNN.

### ISSUE THREAD

**Issue by adarob** [tensorflow/magenta-js#10]
@teropa, do you want to take this one too or should I?

**Comment by teropa** [comment]
Sure, I'll take a stab at rolling in the code I have over the weekend.

Will be testing with these:
https://storage.googleapis.com/download.magenta.tensorflow.org/models/music_rnn/dljs/attention_rnn/manifest.json
https://storage.googleapis.com/download.magenta.tensorflow.org/models/music_rnn/dljs/drums_rnn/manifest.json (this one I've been using already)

**Comment by adarob** [comment]
FYI, the binary clock code is now checked in via #25 so the drum model should be unblocked.
