### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null during saving a midi file

### ISSUE THREAD

**Issue by Apisov** [tensorflow/magenta-js#103]
In all code pens from [Multitrack VAE](https://magenta.tensorflow.org/multitrack) I wasn't able to save the result as a midi file.

In the console, I see this log:

```Uncaught TypeError: Cannot read property '1' of null
    at Object.midiPitchFromNote (magentamusic.js:13370)
    at Object.ensureMidiPitch (magentamusic.js:13370)
    at a.addNoteOn.a.noteOn (magentamusic.js:13370)
    at Array.<anonymous> (magentamusic.js:13370)
    at a (magentamusic.js:13370)
    at r (magentamusic.js:13370)
    at o.value (magentamusic.js:13370)
    at magentamusic.js:13370
    at Array.forEach (<anonymous>)
    at r.value (magentamusic.js:13370)
```

At the top level the exception happens when `sequenceProtoToMidi` method is called.
But the cause is somewhere in the autogenerated code I suppose:

![1](https://user-images.githubusercontent.com/7279438/41911948-1a5e4cac-791c-11e8-9158-796a20258c03.png)

**Comment by adarob** [comment]
I haven't been able to reproduce this. Is it happening every time for you?

**Comment by Apisov** [comment]
Unfortunately, yes. I've tried Chrome, Opera browsers.
I remember this problem since the blog was posted.
Will try to do something with my machine(try other browsers, etc).

**Comment by adarob** [comment]
Does the download work for you on this one?
https://goo.gl/magenta/simpletriodl

**Comment by Apisov** [comment]
Yes, it works now.

Also, I forgot about another issue - the playback from the pens is glitchy slow. It sounds as when CPU is drastically overloaded.

**Comment by adarob** [comment]
Apisov, does it only work now in that link I sent or all of them?

**Comment by Apisov** [comment]
I'm sorry if I wasn't specific, I meant only it works only in that you've posted here.
https://goo.gl/magenta/simpletriodl

The pens from the post still doesn't work.

**Comment by iansimon** [comment]
Does it work in https://goo.gl/magenta/simpletriodl if you use the version of magenta/music used in multitrack?  Try changing line 3 of the HTML to:

`<script src="https://cdn.jsdelivr.net/npm/@magenta/music@1.1.1"></script>`

Trying to see if it's something to do with the MIDI conversion code or the sequences generated by multitrack.

**Comment by Apisov** [comment]
It's strange but I wasn't able to download the model when I had changed it to `1.1.1`.

It just stays on "Loading model (25 MB)..."

**Comment by iansimon** [comment]
That's very strange, the Simple Trio pen should have no problem loading on 1.1.1.  You could try 1.1.5 but I'm completely stumped as to what could be going on.  Maybe you have something weird cached, and it will help to check "Disable cache (while DevTools is open)" in Chrome console preferences; to be clear, I don't think that's the problem here but can't hurt to try...

**Comment by Apisov** [comment]
The Simple Trio pen has no problem loading on 1.1.1 or 1.1.5.

These pens have the problem loading 1.0.3:
https://codepen.io/iansimon/pen/GGRYJZ
https://codepen.io/iansimon/pen/Bxgbgz

Removing the cache didn't help...
Well, it's most likely something on my side will try to find the difference between the Simple Trio and others pens.

**Comment by Apisov** [comment]
There is might be a problem with the model.
So, I've replaced `trio_4bar` to `multitrack_fb256` in the Simple Trio pen and now I have the same error in the console during saving:
```
 at Object.midiPitchFromNote (magentamusic.js:13370)
    at Object.ensureMidiPitch (magentamusic.js:13370)
    at a.addNoteOn.a.noteOn (magentamusic.js:13370)
    at Array.<anonymous> (magentamusic.js:13370)
    at a (magentamusic.js:13370)
    at r (magentamusic.js:13370)
    at o.value (magentamusic.js:13370)
    at magentamusic.js:13370
    at Array.forEach (<anonymous>)
    at r.value (magentamusic.js:13370)
```

**Comment by notwaldorf** [comment]
This issue is very old and we couldn't repro it, so I'm going to close for now. Please re-open a new one with more details/repro steps if it's still important and happening!

**Comment by Dexterisoofy** [comment]
It's still happening for me -_-
