### ISSUE TITLE
How to mirror Checkpoints ?

### ISSUE THREAD

**Issue by liuxiaozhu** [tensorflow/magenta-js#109]
When I click the link in `/music/checkpoints/README.md` it returns 404 like this
`https://storage.googleapis.com/magentadata/js/checkpoints/music_vae/trio_4bar`

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: magentadata/js/checkpoints/music_vae/trio_4bar
</Details>
</Error>
```

**Comment by adarob** [comment]
Indeed, it does not seem possible to make the file list accessible. I can create a zip of this directory for you. Do you need any others?

**Comment by adarob** [comment]
https://storage.googleapis.com/magentadata/js/checkpoints/music_vae/trio_4bar.tar.gz
