### ISSUE TITLE
Add attention melody checkpoint.

### ISSUE THREAD

**Issue by teropa** [tensorflow/magenta-js#14]
AFAICT, attention-based models (#10)  are using encodings not currently supported by magenta-js converters:

* Melody attention_rnn uses a [KeyMelodyEncoderDecoder](https://github.com/tensorflow/magenta/blob/master/magenta/models/melody_rnn/melody_rnn_model.py#L169) with attack, ascending/descending, lookback, and a binary clock.
* Drums RNN uses a [one-hot multi-drum encoding](https://github.com/tensorflow/magenta/blob/master/magenta/models/drums_rnn/drums_rnn_model.py#L86) with a binary clock

Adding appropriate `DataConverter`s for these seems straightforward enough, but how can we also have the appropriate information in the model `converter.json`s so the right ones will be picked?

**Comment by adarob** [comment]
How about we add something like nextInput to the DataConverters that
concats all the additional info. Would this work? I haven't had a chance to
look back at the old code.

**Comment by teropa** [comment]
> If you don't think it's hard to implement, then you could go for it. We can
> just change the converter.json file.

I'll try with the drums one as I'm already familiar with it. Just needs the 2^9 one-hot encoder and then the binary counter.

> How about we add something like nextInput to the DataConverters that
> concats all the additional info. Would this work? I haven't had a chance to
> look back at the old code.

I think it should be possible to compose `DataConverter`s similar to how encoders are composed in Python. Will need to try. Not sure how to express this in the `converter.json` though. Would need to specify either an array of converters, or then just introduce new types for each composed version e.g. `MultiDrumOneHotBinaryCounterConverter` :)

**Comment by adarob** [comment]
I see your point. One option could be to add a pipe character to the type
field in the spec and add an new ConverterArgs type that is composed of 2
different args.

The other is just to add these two specific converters and be done with it
since I don't foresee us adding others like this in the future.

**Comment by adarob** [comment]
The current plan is to remove the case of having dependencies between the inputs and outputs aside from the one-hot sample. We will only allow an independent control sequence to be concatenated (#20).

I am going to try training an attention melody model without these dependencies to see how it compares.

**Comment by adarob** [comment]
I will add a

**Comment by adarob** [comment]
Covered by #11
