### ISSUE TITLE
Precision problems in MultitrackConverter on Safari

### ISSUE THREAD

**Issue by teropa** [tensorflow/magenta-js#141]
I'm getting the following kinds of results for the tokens tensor in  `MultitrackConverter.toNoteSequence` on Safari 11.1 on OS X: 

<img width="278" alt="screen shot 2018-08-28 at 20 11 45" src="https://user-images.githubusercontent.com/47968/44738861-d793c180-aafe-11e8-899d-13fcda57eadf.png">

These in turn become pitches like `50.999996185302734` in the `NoteSequence`. 

I was able to fix it for myself using some `Math.round()`s in a few places (and can make a PR of that if needed), but I feel there's probably a better way to fix this. I tried casting the tensor with `asType('int32')` before fetching the data, but to no avail.

**Comment by adarob** [comment]
Aren't the tokens in an Int32Array? When are they getting converted to float?

**Comment by teropa** [comment]
I think they should be (and the TypeScript type annotation attests this as well), but it's a `Float32Array`. It's also a `Float32Array` on Chrome but there the numbers within are all integer.

What I'm printing is the outcome of

```ts
const tokens = await tensor.data() as Int32Array;
```

Adding this didn't change it either:

``` ts
const tokens = await tensor.asType('int32').data() as Int32Array;
```

**Comment by adarob** [comment]
@nsthorat @dsmilkov have you seen this before?

**Comment by nsthorat** [comment]
Yikes, that shouldn't be happening.

Are you using the latest version of tfjs, 0.12.6?

**Comment by teropa** [comment]
@nsthorat I've found out a minimal reproduction:

``` js
let x = tf.range(0, 489);      
x.argMax().data().then(console.log);
```

On Chrome yields:

```
Float32Array [488]
```

On Safari yields:

```
Float32Array [488.00006103515625]
```

The behavior is the same on 0.12.5 (which is what Magenta Music is currently on) and 0.12.6.

Curiously, `dataSync` does *not* have this problem - only the asynchronous version.

Want me to report this over on tfjs?

**Comment by notwaldorf** [comment]
Closing this as we've switched to tfjs 1, which may or may not have fixed it. Please re-open a new one with more details/repro steps if it's still important and happening! ❤️
