### ISSUE TITLE
Fix bundling/improve bundling strategy in magenta/music

### ISSUE THREAD

**Issue by notwaldorf** [tensorflow/magenta-js#185]
Two things:
1. Currently our bundle is broken (symptoms: uglify won't minify it on jsdelivr). Since we added `FFT` (which has es6 code), we don't have anything in the build process to convert that dependecy to `es5` (we use tsify for the ts source but nothing else). Maybe rollup + babel would work?
2. It would be nice to also at this point be able to produce a nice es6 build for modules (since all modern browsers support it, and then we could pick and choose which module of magenta/music you want to load (vs. the whole bundle and tf-core at once).

**Comment by adarob** [comment]
Fixed by #191

**Comment by notwaldorf** [comment]
This isn’t exactly finished — 191 only fixed the es5 build, but we still only produce one huge es5, non module build.

**Comment by notwaldorf** [comment]
Fixed by #337
