### ISSUE TITLE
We should update to the latest version of tone

### ISSUE THREAD

**Issue by notwaldorf** [tensorflow/magenta-js#214]

**Comment by rogerpasky** [comment]
Yes please, current Chrome version is rejecting to make any sound before some interaction (click) has been done. This makes all demos muted (I checked it in _mm.Player with callback_).

> Tone.js:4043 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. [https://goo.gl/7K7WLu](https://goo.gl/7K7WLu)

According to the Google Developers referenced documentation this is a new Chrome policy to avoid autoplay.
> Note: The Web Audio API will be included in the Chrome autoplay policy with M71 (December 2018).

Tone.js detects some problem and goes mute forever.
> 	    // set the audio context initially, and if one is not already created
> 	    if (Tone.supported && !Tone.initialized) {
> 	        Tone.context = new Tone.Context();
> 	        // log on first initialization
> 	        // allow optional silencing of this log
> 	        if (!window.TONE_SILENCE_VERSION_LOGGING) {
> 	            // eslint-disable-next-line no-console
> 	            console.log('%c * Tone.js ' + Tone.version + ' * ', 'background: #000; color: #fff');
> 	        }
> 	    }

This appears to happen in the Tone library initialisation, so there's no way to way to work-around it in our own code.

**Comment by notwaldorf** [comment]
Closing -- I think we're actually on the latest [stable version](https://www.npmjs.com/package/tone)

**Comment by notwaldorf** [comment]
@tambien `0.12.80` is the latest stable, and you haven't released `@next` (13.x) and it's still in dev mode, right?

**Comment by tambien** [comment]
@notwaldorf yes still dev, but hoping to find time to make a release very soon.

**Comment by notwaldorf** [comment]
@tambien cool cool, let us know when it's out and the canaries have survived the mines and I'll reopen this 😂

**Comment by tambien** [comment]
@notwaldorf ready! tone@latest === tone@13.4.9
