### ISSUE TITLE
Exception using Getting Started at https://github.com/tensorflow/magenta-js/tree/master/image

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/magenta-js#239]
With the "via Script Tag" sample code on https://github.com/tensorflow/magenta-js/tree/master/image

I see the following exception. But when I remove @^0.1.2 it works.

magentaimage.js:44405 Initialized Arbitrary Style Transfer network
magentaimage.js:3218 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at magentaimage.js:3218
    at Array.forEach (<anonymous>)
    at e.checkInputShapeAndType (magentaimage.js:3210)
    at e.execute (magentaimage.js:3002)
    at e.execute_ (magentaimage.js:2778)
    at e.predict (magentaimage.js:2751)
    at magentaimage.js:44432
    at magentaimage.js:7193
    at e.scopedRun (magentaimage.js:7203)
    at e.tidy (magentaimage.js:7192)
(anonymous) @ magentaimage.js:3218
e.checkInputShapeAndType @ magentaimage.js:3210
e.execute @ magentaimage.js:3002
e.execute_ @ magentaimage.js:2778
e.predict @ magentaimage.js:2751
(anonymous) @ magentaimage.js:44432
(anonymous) @ magentaimage.js:7193
e.scopedRun @ magentaimage.js:7203
e.tidy @ magentaimage.js:7192
e.tidy @ magentaimage.js:7590
e.stylize @ magentaimage.js:44431
stylize @ index.html:17
Promise.then (async)
(anonymous) @ index.html:22

**Comment by adarob** [comment]
Thanks! I updated it to https://cdn.jsdelivr.net/npm/@magenta/image@^0.2.1 can you please re-open if that doesn't work.
