### ISSUE TITLE
Possible default parameter mismatch at data.ts functions

### ISSUE THREAD

**Issue by rogerpasky** [tensorflow/magenta-js#243]
As far as I understand, **DEFAULT_QUARTERS_PER_MINUTE** is related to playing tempo, not to **quantizationInfo** resolution, but it's used as default value to fulfill stepsPerQuarter parameter like:

```ts
async toNoteSequence(
    oh: tf.Tensor2D,
    stepsPerQuarter = constants.DEFAULT_QUARTERS_PER_MINUTE) {
  const noteSequence = NoteSequence.create();
  noteSequence.quantizationInfo =
      NoteSequence.QuantizationInfo.create({stepsPerQuarter});
// ...
}
```

IMHO it should be replaced to **DEFAULT_STEPS_PER_QUARTER**, as declared in constants.ts

It happens several times through data.ts in following functions:

- DrumsConverter.toNoteSequence()
- DrumRollConverter.toNoteSequence()
- MelodyConverter.toNoteSequence()
- TrioConverter.toNoteSequence()

This is not a dramatic issue, because using a higher resolution (DEFAULT_QUARTERS_PER_MINUTE = 120) instead a lower one (DEFAULT_STEPS_PER_QUARTER = 4) will work flawlessly, but it could raise some internal unexpected inconsistencies.

**Comment by adarob** [comment]
Thanks for noticing this issue! Are you interested in fixing it as well or would you prefer we do it?

**Comment by rogerpasky** [comment]
To be honest, I've never commited a pull request. Never too late to learn how to. I'd love to contribute to this great project fixing it by myself.

I hope I won't break it all :-D

**Comment by adarob** [comment]
Go for it! Let me know if you have any questions. You should make sure the tests pass (`yarn test`) and the demos work (`yarn run-demos`).

**Comment by rogerpasky** [comment]
Changes done, tests done, (my first ever) pull request (learned and) done, CLA signing done, merge done... I'm closing this issue.
