### ISSUE TITLE
How to have visualizer redraw with different noteSequence

### ISSUE THREAD

**Issue by agreyfield91** [tensorflow/magenta-js#252]
In the [docs](https://tensorflow.github.io/magenta-js/music/classes/_core_visualizer_.visualizer.html), there is only one method listed for visualizers - redraw(). It looks like its only purpose is to update the visualizer's active note. Is it possible to have it "redraw" with a different ns (so I could perhaps create a visualizer, expand upon the ns with musicRNN, and update the visualizer with the new ns)?

Or would I have to destroy the instance and create a new visualizer? If that's the case, how would I destroy?

Thank you!

**Comment by notwaldorf** [comment]
Yeah, destroying the instance and creating the new one is the way to go. Most of the work is done in resizing the canvas anyway, so the constructor isn't that expensive. You don't have to "destroy" it per se, you just have to re-create it. So
```
let visualizer = new mm.Visualizer(someNoteSequence, aCanvasElement);
// ...
visualizer = new mm.Visualizer(aDifferentNoteSequences, aCanvasElement);
```
