### ISSUE TITLE
MusicRNN continueSequence with polyphony

### ISSUE THREAD

**Issue by kadinzhang** [tensorflow/magenta-js#253]
Experimenting with MusicRNN's continueSequence, the model only continues music with monophonic structure - if I give it a complex piano piece, it will return a very simple, rapid melody. Is it currently possible to get it to continue in polyphonic structure? Am I looking at the wrong model?

Thanks!

**Comment by adarob** [comment]
Unfortunately we haven't added any polyphonic models to Magenta.js yet! It should be fairly easy to do but we're all so busy! We already have #26 which will cover it, so I'm closing this one out.
