### ISSUE TITLE
Converting python onset and frames MAESTRO checkpoint to tfjs leads to incompatible model

### ISSUE THREAD

**Issue by TGabor** [tensorflow/magenta-js#265]
Thanks for sharing all these resources with the community!

I tried converting the [OAF MAESTRO checkpoint](https://storage.googleapis.com/magentadata/models/onsets_frames_transcription/maestro_checkpoint.zip) using [checkpoint_converter.py](https://github.com/tensorflow/magenta-js/blob/master/scripts/checkpoint_converter.py):
```
python checkpoint_converter.py train/model.ckpt maestrocp
```

Once I use my manually converted checkpoint in [piano-scribe](https://piano-scribe.glitch.me), I get the error

```
Uncaught (in promise) Error: Variable not found: onsets/cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
    at getVar (music@1.2:81458)
    at setLstmWeights (music@1.2:81469)
    at Lstm.setWeights (music@1.2:81471)
    at music@1.2:81326
    at music@1.2:8586
    at Engine.scopedRun (music@1.2:8596)
    at Engine.tidy (music@1.2:8585)
    at Object.Environment.tidy (music@1.2:8928)
    at OnsetsAndFrames.build (music@1.2:81322)
    at OnsetsAndFrames.<anonymous> (music@1.2:81199)
```

The python checkpoint uses bidirectional LSTM layers, whereas the provided [tfjs checkpoints](https://github.com/tensorflow/magenta-js/blob/master/music/checkpoints/README.md) ([onsets_frames_uni](https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni), [onsets_frames_uni_q2](https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni_q2)) use unidirectional models.

Is there an easy fix for this? Would it be possible to share the python checkpoints that were used to generate `onsets_frames_uni` and `onsets_frames_uni_q2`?

**Comment by adarob** [comment]
Here you go:

https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni/model.ckpt-583632.data-00000-of-00001
https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni/model.ckpt-583632.index

**Comment by TGabor** [comment]
Hi @adarob,

thanks for sharing!

Would it be possible to add the **meta file** for the checkpoint, too?

**Comment by TimothyRoberts** [comment]
Hi @TGabor, 

would you mind explaining why I'm getting this error?

<img width="622" alt="screenshot 2019-02-26 at 11 36 40" src="https://user-images.githubusercontent.com/35260270/53410144-d6aef000-39ba-11e9-91b6-4efb98fa2c6c.png">

I have pip installed tensorflowjs already, does this checkpoint_converter file need to be saved somewhere in particular?

**Comment by TGabor** [comment]
@TimothyRoberts You either need to change to the `magenta-js/scripts` directory or call `python scripts/checkpoint_converter.py` from the `magenta-js` directory

**Comment by TimothyRoberts** [comment]
Thank you, sir! I hadn't cloned the magenta-js directory
