### ISSUE TITLE
Merge packages into a single package.

### ISSUE THREAD

**Issue by teropa** [tensorflow/magenta-js#27]
Many projects need functionality both from `core` and `music_rnn`/ `music_vae`. For example, you may need to use the NoteSequence or ControlSignal libraries as well as the main model class.

Also, some projects may use _both_ RNN and VAE.

Currently this doesnt seem possible as RNN and VAE are in separate bundles, both of which contain their own copy of core as well as Tensorflow.

Would it make sense to create a `magenta-full.js` bundle to easily include everything?

**Comment by adarob** [comment]
This is a good point. Is it not possible to import the two bundles
separately?

**Comment by teropa** [comment]
It's possible if you Yarn/NPM install it and `import`.

But when using the browserified bundles (e.g. on Codepen) each of `magenta.js`, `musicrnn.js`, and `musicvae.js` has its own copy of Tensorflow causing some load errors (as well as a lot more weight)

**Comment by adarob** [comment]
Makes sense. Do you know how to set this up?

We could also consider making a single package instead of separating out
the models.

**Comment by teropa** [comment]
Yes, might make sense to add a new `index.ts` somewhere that pulls in everything, and then a build target that browserifies it.

**Comment by adarob** [comment]
I could imagine having a package called @magenta/models that combines all of the model packages. This is basically what you are suggesting. We can decide on something on Monday when @cghawthorne can also weigh in.

**Comment by teropa** [comment]
> @teropa, do you have any objection to us just combining the full library into a single package and removing the separate core, music_rnn, and music_vae packages? We are new to the JS world, so we aren't sure how this would typically be done.

No objections at all, sounds good. I think that's a fairly typical pattern anyway.

**Comment by adarob** [comment]
Our current plan is to move all of our current packages into a single @magenta/music package, leaving room for future models that don't work with NoteSequences.

@cghawthorne, we should probably restructure the directories, e.g., move music_vae.ts and music_rnn.ts into a models directory. data.ts should probably be renamed to converters.ts since we have other data libs.
