### ISSUE TITLE
Error: NoteSequence undefined is not quantized (missing quantizationInfo)

### ISSUE THREAD

**Issue by curiouscod3** [tensorflow/magenta-js#276]
Hi, I've been attempting to understand && test "magenta-js" project.
I've tested the code in ["Making music with magenta.js" page.](https://hello-magenta.glitch.me/#interpolating-between-two-sequences)
Whenever I click the play button("Interpolating between two sequences"), 
I've got Error : "Error: NoteSequence undefined is not quantized (missing quantizationInfo)".

Even though I created my own project with the same codebase with 1.5.0(latest version), the error still occurred. I have no idea what is wrong with it. 

Seemingly, music_vae.interpolate() function needs quantized variable. 
Could you fix this  or Could you show me how to run "Interpolating" play?

**Comment by notwaldorf** [comment]
Yup, you're totally right. Good catch!

I've updated the code sample to quantize the note sequences first, and then interpolate: https://glitch.com/edit/#!/hello-magenta?path=script.js:183:5
