### ISSUE TITLE
Uncaught (in promise): ReferenceError: WebMidi is not defined

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [tensorflow/magenta-js#278]
I just installed the latest magentamusic npm package for my Angular project.
I've got same error; I don't use the ts files directly. In Angular typescript project, I cannot use magentamusic.js script javascript file because Angular needs Typescript and d.ts type file.

ERROR in node_modules/@magenta/music/es5/core/player.d.ts(51,14): error TS2503: Cannot find namespace 'WebMidi'. node_modules/@magenta/music/es5/core/player.d.ts(52,32): error TS2503: Cannot find namespace 'WebMidi'. node_modules/@magenta/music/es5/core/recorder.d.ts(34,22): error TS2503: Cannot find namespace 'WebMidi'. node_modules/@magenta/music/es5/core/recorder.d.ts(35,24): error TS2503: Cannot find namespace 'WebMidi'. node_modules/@magenta/music/es5/core/recorder.d.ts(39,32): error TS2503: Cannot find namespace 'WebMidi'.

Even though magentajs music core sources are written in Typescript having d.ts, the output files built doesn't look up d.ts correctly. IDK . Maybe WebMidi package hasn't been installed after installing npm @magenta/music package.

I think Angular cannot find the package installed.

**If I install "@types/webmidi", this error is gone. But another error comes out !**

"core.js:15723 ERROR Error: Uncaught (in promise): ReferenceError: WebMidi is not defined
ReferenceError: WebMidi is not defined"

I have to install webmidi package separately although magenta music package uses it; 
`import WebMidi from 'webmidi';` Also I added the following line in angular.json config file
```
"scripts": [
              "./node_modules/webmidi/webmidi.min.js"
            ],
```

Please check out the how magentajs music package exports webmidi and types in the package.json of @magenta/music!

I am using pretty much latest Chrome browser and magenta package on MacOSx

**Comment by notwaldorf** [comment]
I don't think we publish any types with magenta (and honestly, I don't know enough about types to check if we do). @cannoneyed do you have any ideas?

**Comment by loganstillings** [comment]
I'm also running into this problem. As of now, I cannot use @magenta/music in an Angular app

**Comment by notwaldorf** [comment]
I've made some changes to the es6 modules in https://github.com/tensorflow/magenta-js/pull/365 and i think it should work better now. I've tested it out in this repo: https://github.com/notwaldorf/example-magenta-in-ts. I know it's not Angular, but it is using Typescript, and I could repro this problem in that repo. Give it a try and let me know!

**Comment by notwaldorf** [comment]
Closing this, since I think it was fixed and there's been no updates on this issue
