### ISSUE TITLE
How to import/export/stream sequence&midi data across the grpc or socket?

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [tensorflow/magenta-js#279]
I am attempting to develop a collaboration music app. 
WebServer/Browser <--(Bi-direction)--> MobileApp Clients.
I may need streaming method via bi-direction. 

Clients apps are not WebBrowser and need some fast seamless connection via grpc or socket.
I am thinking to utilize gRPC because Json with Http1.x is slow and heavy for this; it is not even suitable for streaming. As you know, grpc supports bi-direction streaming mechanism. 
Seemingly, magenta takes advantage of Protobuf to serialize data, right? but where is the methods about this?

What about "sequenceProtoToMidi"? this is all about json-based data?
I couldn't find functions to import and export protobuf in midi_io.ts.

Could you show me some APIs or examples or even some tips/guides?

**Comment by mattetti** [comment]
I think what you're looking for is in `midi_io.ts` https://github.com/tensorflow/magenta-js/blob/master/music/src/core/midi_io.ts#L38 You will find there a MIDI to proto's sequencer converter and vice-versa. Your server application could receive MIDI data and convert it on the fly or you could build a proto object yourself. The master proto file is available in the main magenta repo: https://github.com/tensorflow/magenta/blob/master/magenta/protobuf/music.proto and the generated JS code is available here https://github.com/tensorflow/magenta-js/blob/master/music/src/protobuf/proto.js

**Comment by notwaldorf** [comment]
Looks like this was answered, closing! 🎉
