### ISSUE TITLE
How to use MusicRNN continuesequence

### ISSUE THREAD

**Issue by agreyfield91** [tensorflow/magenta-js#282]
In the [docs](https://tensorflow.github.io/magenta-js/music/classes/_music_rnn_model_.musicrnn.html#continuesequenceandreturnprobabilities), it gives the parameters for continuesequence() as:

 `continueSequence(sequence: INoteSequence, steps: number, temperature?: number, chordProgression?: string[]): Promise<INoteSequence>`. 

I'm confused about the temperature and chordProgression parameters, as there isn't much elaboration in the documentation. For temperature, what is the range of numbers that can be imputed? I tried a variety of numbers, and all but 1 caused the method to return nothing back. For chordProgression, how would I format the progression? Is there an example I can see that demonstrates how to use it?

Thanks!

**Comment by notwaldorf** [comment]
First things first, here's an example of using `continueSequence` with both a `temperature` and a `chordProgression` parameter: https://github.com/tensorflow/magenta-js/blob/master/music/demos/music_rnn.ts#L156

- `temperature` is a number that's above 0, and doesn't really have any upper bound. However, anything above 1.5 will essentially result in random results, so you won't see much difference between a temperature of 1.9 and one of like 3
- `chordProgressions` is an array of chords that are passed to the [tonal](https://github.com/danigb/tonal) package for parsing, so they're in that format. I can't find a complete list of what's available in the docs, but as you can see in the example it's the pretty common way of representing keys by a capital letter (`B`), minors by adding an m (`Bm`), flats with a b (`Bb`) etc.

I think it would be a good idea to add a bit of docs to the `chordProgressions` parameter, at least pointing to `tonal`. Would you be interested in making that PR?

**Comment by mattetti** [comment]
I was looking for an easy PR to get myself familiar with the code base and processes. Thanks @agreyfield91 for the opportunity and I hope it will help future developers taking a look at this model.
