### ISSUE TITLE
How can I use local soundfonts?

### ISSUE THREAD

**Issue by BogdanAngh** [tensorflow/magenta-js#297]
Hello, I would like to have other instruments for the SoundFontPlayer class, how can I do that? Thank you.

**Comment by Seanitzel** [comment]
I would also be more than happy to know!

**Comment by notwaldorf** [comment]
I'm not suuuper familiar with this code, but by looking at the [SoundFont player code](https://github.com/tensorflow/magenta-js/blob/master/music/src/core/soundfont.ts#L99) and our soundfonts, it looks like it's first looking for a `soundfont.json` file to get the list of instruments in that sound font, and then for each instrument, an 'instrument.json' file in the folder with that name. For example, for the sgm_plus soundfont, this is the [soundfont.json](https://storage.googleapis.com/magentadata/js/soundfonts/sgm_plus/soundfont.json) file; it lists that instrument 0 is 'acoustic_grand_piano', so this is the [instrument.json](https://storage.googleapis.com/magentadata/js/soundfonts/sgm_plus/acoustic_grand_piano/instrument.json) file.

So your folder setup should be:
```
your_local_soundfont
|____ soundfont.json
|____ instrument_name
        |____ instrument.json
        |____ p20_v1.mp3
        |____ p20_v2.mp3
        |____...
        |____ p${PITCH}_v${VELOCITY}.mp3, for all the pitches and velocities you want to support
```

Does this help? If it does, I can send a PR to add this to the documentation
