### ISSUE TITLE
MusicVAE adding extra note onto end of 2nd original melody and other melody interpolations

### ISSUE THREAD

**Issue by mrbombmusic** [tensorflow/magenta-js#299]
Hello,

I recently started playing with the MusicVAE model to create melody interpolations between two melodies. I started by following this tutorial: https://glitch.com/~hello-magenta

However, after the model has run and the melodies and interpolations are created, I noticed that the 2nd original melody now includes an additional note at the end with a duration much longer than any of the other notes in either of the original two melodies. This note is not part of the original melody provided to the model.

This occurs when I am only creating 1 interpolation between the two original melodies. I've also noticed when I do more interpolations, several of the interpolated melodies leading up to and including the 2nd original melody also include an extra long note at the end.

Here is an example of my code: [https://editor.p5js.org/mrbombmusic/sketches/0g1Vd7Azf](https://editor.p5js.org/mrbombmusic/sketches/0g1Vd7Azf)

Should I be using a different Model checkpoint? Does it have anything to do with the fact that I am separating the pitch, duration and starting point into separate arrays? This doesn't make sense though because looking at the info printed out after the melodies are made also shows this issue.

Thanks for the help. Besides this issue, I'm really enjoying this!

**Comment by adarob** [comment]
Hey, thanks for reporting this. Unfortunately it's quite difficult to diagnose. It *could* be a bug in the DataConverter code, or it could just be an artifact introduced by the model. Maybe you could try using one of the other pre-trained melody checkpoints to see if you get similar behavior?

**Comment by mrbombmusic** [comment]
Thank you. I tried several of the different melody checkpoints and did not get the same behavior. 
So it appears the issue was with the checkpoint - mel_16bar_small_q2.
Perhaps it being a 16 bar model made it add those notes to fill out some beats to get it closer to that amount of time ? ¯\_(ツ)_/¯

Thanks again for the help.
