### ISSUE TITLE
Uncaught error in MusicRNN

### ISSUE THREAD

**Issue by Buddhilive** [tensorflow/magenta-js#300]
My app hosted [here](https://ai.buddhilive.com/studio/) throws this exception. I was working fine until today.

C:\fakepath(57,12-37): error X4505: maximum temp register index exceeded
......

music@^1.0.0:22 Uncaught (in promise) Error: Failed to link vertex and fragment shaders.
    at jr (music@^1.0.0:22)
    at t.createProgram (music@^1.0.0:22)
    at music@^1.0.0:22
    at music@^1.0.0:22
    at t.getAndSaveBinary (music@^1.0.0:22)
    at t.compileAndRun (music@^1.0.0:22)
    at t.concat (music@^1.0.0:22)
    at t.concat (music@^1.0.0:22)
    at music@^1.0.0:22
    at music@^1.0.0:22
jr @ music@^1.0.0:22
t.createProgram @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:22
t.getAndSaveBinary @ music@^1.0.0:22
t.compileAndRun @ music@^1.0.0:22
t.concat @ music@^1.0.0:22
t.concat @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:22
t.scopedRun @ music@^1.0.0:22
t.runKernel @ music@^1.0.0:22
concat_ @ music@^1.0.0:22
concat @ music@^1.0.0:22
stack_ @ music@^1.0.0:22
concat @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:22
t.scopedRun @ music@^1.0.0:22
t.tidy @ music@^1.0.0:22
e.tidy @ music@^1.0.0:22
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
r @ music@^1.0.0:83
t.continueSequenceImpl @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
(anonymous) @ music@^1.0.0:83
r @ music@^1.0.0:83
t.continueSequence @ music@^1.0.0:83
generateMusic @ index.js:122
document.getElementById.onclick @ index.js:55
async function (async)
generateMusic @ index.js:122
document.getElementById.onclick @ index.js:55

**Comment by Buddhilive** [comment]
Okay, I found the solutions. The problem is with the latests version of Majenta.js 1.8.0
I specified version 1.7.0
Bingo it works!

**Comment by adarob** [comment]
Great!

**Comment by Buddhilive** [comment]
Okay, I found the solutions. The problem is with the latests version of Majenta.js 1.8.0
I specified version 1.7.0
Bingo it works!
