### ISSUE TITLE
suggestion: vscode workspace settings

### ISSUE THREAD

**Issue by mattetti** [tensorflow/magenta-js#308]
As a first time contributor, I noticed that my prettifier and TS autoformat weren't compatible with what the authors have used. It would be nice to have a set of standards so anyone contributing wouldn't have to guess the code style guide. Not everyone uses VSCode so maybe also have some sort of "prettier settings" available across editors/IDEs might be nice.

**Comment by notwaldorf** [comment]
It looks like we're using `clang-format` (with the "Google" style guide, [see here](https://github.com/tensorflow/magenta-js/blob/master/music/.vscode/settings.json#L23)) for the prettify/autoformat rules. I think that's a separate beast to `prettier`, but if the Google style guide exists as a `prettier` config, we could probably add it.

**Comment by mattetti** [comment]
prettier seems to have become the standard according to this npm trend chart: https://www.npmtrends.com/beautify-vs-clang-format-vs-prettier but it looks like Google already has a style guide set of tools to handle this very use case :)
https://github.com/google/gts

Let me know how you feel about it and I'd be glad to set it up.

**Comment by mattetti** [comment]
Another simpler option is to add the information in the README: install 'clang-format' (via brew for and chocolatey or whatever the Windows recommended way is) then install the editor plugin.

It's not that bad actually, if I had known that was the process, I would have done it.

I think I'd still personally prefer the gts approach, especially if the dependency is only a dev dependency (which I assume it is)

**Comment by notwaldorf** [comment]
@mattetti i think for now documenting the existing process is the easiest and safest thing to do. if you want to send a PR for that, i'd gladly accept it!
