### ISSUE TITLE
Clicks / pops in the SoundFont player introduced by Tone r13

### ISSUE THREAD

**Issue by cannoneyed** [tensorflow/magenta-js#329]
Sadly, it looks like the upgrade to Tone.js 13 in https://github.com/tensorflow/magenta-js/pull/326 has introduced some clicks/pops in the SoundFont player. It's a little harder to notice than the same issues that were present in the PolySynth player, but they're there nonetheless....

@tambien Do you think this might be as simple to fix as the Polysynth pops? Hopefully I can take a look later this afternoon.

**Comment by tambien** [comment]
If it's the same issue as the PolySynth, it had to do with [a bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=990393) with scheduling envelope. If there are not the same pops on FF and Safari, i'd say it might be related to that.

**Comment by cannoneyed** [comment]
@tambien Nope! It's just a small regression in supplying a fadeOut to a `BufferSource`, fixed:

https://github.com/tensorflow/magenta-js/pull/330

**Comment by notwaldorf** [comment]
Fixed in #330
