### ISSUE TITLE
Missing type declaration in music-vae npm module

### ISSUE THREAD

**Issue by hrldcpr** [tensorflow/magenta-js#34]
As far as I can tell, the `@magenta/music-vae` module currently in NPM (v1.1.4) has no `.d.ts` file included.

You can try:
```bash
mkdir test
cd test
npm init -y
npm install @magenta/music-vae
find node_modules/@magenta/music-vae -name '*.d.ts'
```

I assume this is unintentional, since package.json includes `"types": "es5/index.d.ts"`, and `@magenta/core` includes type declarations.

Anyway just fyi, thanks!

**Comment by adarob** [comment]
I don't think you need those files in the npm package. Have you tried doing
'yarn add @magenta/music-vae && yarn install'.

**Comment by hrldcpr** [comment]
@adarob Thanks, yeah I tried it with yarn as well.

Perhaps since package.json specifies `"main": "es5/index.js"`, there's no way for typescript to know to use `src/index.ts` instead…

Have you had success getting the types via the npm module in a typescript project? (I only noticed that I'm not getting the types because I have `noImplictAny` set in my tsconfig.)

**Comment by hrldcpr** [comment]
I went ahead and built this project locally and then copied `es5/*.d.ts` into my other project's `node_modules/@magenta/music-vae/es5/` folder, and now typescript is happy ✨ 

So as far as I can tell, you should include those files in the published package. (Which is also consistent with `@magenta/core` including the files.)

**Comment by adarob** [comment]
Ah, thanks! I will update shortly.

**Comment by hrldcpr** [comment]
Cool thanks! (And no rush on my end.)

**Comment by adarob** [comment]
Can you see if it's fixed now?

**Comment by hrldcpr** [comment]
Yup looks like it! Thanks 👍
