### ISSUE TITLE
How to train my own model

### ISSUE THREAD

**Issue by merfii** [tensorflow/magenta-js#35]
I followed the procedule in
[here](https://github.com/tensorflow/magenta/tree/master/magenta/models/music_vae)
to train my own model. After training, when using
`new musicvae.MusicVAE(melodiesModelCheckPoint)`
the MusicVAE.js just said

> manifest.json not found in 'XXXXXX'

I just want to know how to generate manifest.json file from model.ckpt.xxxx folder?
Thanks!

**Comment by adarob** [comment]
Hi Mafi,

Sorry that the procedure isn't fully explained. We are currently working on
updating everything to work with the new tensorflow.js, so stay tuned for
that.
For now, you can use this legacy deeplearnjs script to dump the weights
from your trained checkpoint to a format that MusicVAE.js can read:
https://github.com/PAIR-code/deeplearnjs-legacy-loader

-Adam

**Comment by adarob** [comment]
You can either include the converter.json file in the checkpoint directory, or you can pass in a DataConverter to the MusicVAE constructor. Either way, you have to specify the correct parameters based on the model you trained. Which config did you use to train the model?

**Comment by adarob** [comment]
FYI, we've also just updated the package to use the new tfjs checkpoints. Please see the new (still incomplete) readme at https://github.com/tensorflow/magenta-js/tree/master/music.

There are still a few parts of this newer package that are incomplete, but we will have everything in a good state by the end of the week.
