### ISSUE TITLE
ERROR Uncaught TypeError: n.playNote is not a function

### ISSUE THREAD

**Issue by royleibov** [tensorflow/magenta-js#359]
When trying to run a basic player

**Comment by notwaldorf** [comment]
Do you have some more details about how you're calling this? Which version of magenta-js? The player demo still works (https://tensorflow.github.io/magenta-js/music/demos/player.html), so I think you're calling `player.start(someNoteSequence)` a bit funky.

**Comment by royleibov** [comment]
Decided to try a basic approach.. I basically copied the [hello magenta](https://hello-magenta.glitch.me/) example but it seems to produce the same error.

```
let player = new mm.SoundFontPlayer('https://storage.googleapis.com/magentadata/js/soundfonts/salamander', callbackObject={
  run: (note) => viz.redraw(note),
  stop: () => {console.log('done');}
});

```

Edit: After playing around i figured the problem was with the constructor. It all got fixed once I added the callbackObject like this
```
let player = new mm.SoundFontPlayer('https://storage.googleapis.com/magentadata/js/soundfonts/salamander');
player.callbackObject = {
run: (note) => viz.redraw(note),
  stop: () => {console.log('done');}
};
```
