### ISSUE TITLE
Code cleanup: Replace a bunch of console.logs with core.log

### ISSUE THREAD

**Issue by notwaldorf** [tensorflow/magenta-js#363]
That way users could turn off a bunch of noise (the most annoying culprit is the Soundfont player)

**Comment by naclcaleb** [comment]
I can take this

**Comment by naclcaleb** [comment]
Do I simply replace all the `console` s with `core`?

**Comment by naclcaleb** [comment]
Or do I have to import that from somewhere?

**Comment by notwaldorf** [comment]
There's a `logging` module under core (`core/logging.js`). Here's an example of how it's used: https://github.com/tensorflow/magenta-js/blob/master/music/src/transcription/model.ts#L119

**Comment by naclcaleb** [comment]
Yea, I just realized that. I'm creating a pull request now...

**Comment by notwaldorf** [comment]
Fixed by #367
