### ISSUE TITLE
Channel 10 incorrectly loaded as drums

### ISSUE THREAD

**Issue by cifkao** [tensorflow/magenta-js#381]
`midiconvert` used by Magenta.js seems to consider both channel 9 and 10 as drums (as per General MIDI 2), so when loading a MIDI file with `urlToNoteSequence`, notes in channel 10 will have `isDrum == true`. This is inconsistent with the behavior of Magenta, where only channel 9 is loaded as drums (as per General MIDI).

Among other things, this means that MIDI files created with Magenta and containing more than 9 non-drum tracks will be loaded incorrectly in Magenta.js.

**Comment by notwaldorf** [comment]
cc @tambien for midiconvert.

**Comment by tambien** [comment]
Seems related to: Tonejs/Midi#75

**Comment by cifkao** [comment]
The relevant check seems to be here: https://github.com/Tonejs/Midi/blob/4312333940fbe477a0a148120d90df8ef347d5f9/src/Instrument.ts#L65-L68

In contrast, `pretty_midi` (used by Magenta) just checks for channel 9:
https://github.com/craffel/pretty-midi/blob/78e33ab1c24e1156529320ea127dd51d57f7ab99/pretty_midi/pretty_midi.py#L265

I think the latter is what most MIDI files seem to use. So probably this is really a Tonejs/Midi issue, but I wanted to point out the inconsistency it creates between Magenta and Magenta.js.

**Comment by tambien** [comment]
not sure how that got in there, but just changed it to only channel 9. fix should be live in @tonejs/midi@2.0.11

**Comment by notwaldorf** [comment]
I think this should be fixed, then!

**Comment by cifkao** [comment]
magenta/music seems to use `midiconvert` for loading the MIDI files, which, I guess, is an older version of Tonejs/Midi? So is it really fixed? (I haven't tested it recently.)
