### ISSUE TITLE
Support web workers for gansynth.js

### ISSUE THREAD

**Issue by dubreuia** [tensorflow/magenta-js#386]
I can use web workers in the following code:

**simple.html**
```html
<html lang="en">
<body>
<script>
  new Worker("simple.js")
</script>
</body>
</html>
```

**simple.js**
```js
importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@1.4.0/dist/tf.min.js");
importScripts("https://cdn.jsdelivr.net/npm/@magenta/music@^1.12.0/es6/core.js");
importScripts("https://cdn.jsdelivr.net/npm/@magenta/music@^1.12.0/es6/music_vae.js");

const musicvae = new music_vae.MusicVAE("https://storage.googleapis.com/" +
    "magentadata/js/checkpoints/music_vae/trio_4bar");
musicvae.initialize();
```

Which works properly. But if I add the following line, the code breaks:

```js
importScripts("https://cdn.jsdelivr.net/npm/@magenta/music@^1.12.0/es6/gansynth.js");
```

With this error:

```
Uncaught null
Script error.
```

I don't have more information, I'll try to debug the gansynth.js code if I have time.

P.S. ES5 modules don't work because of "This browser does not support Tone.js".

**Comment by notwaldorf** [comment]
I think the only big difference between the music_vae and gansynth models is that gansynth does a lot of audio work that needs an `AudioContext`, and I don't think that works in a WebWorker (but could maybe work in an AudioWorklet? I'm not very familiar with that spec). So unfortunately, I don't think that gansynth will work in a worker :(
