### ISSUE TITLE
Checkpoints unavailable 

### ISSUE THREAD

**Issue by ismazmerli** [tensorflow/magenta-js#395]
Hi are the checkpoints still available to download because I ha an issue with the urls they are supposed to be on : 

![image](https://user-images.githubusercontent.com/45600611/73442189-9c7d6980-4354-11ea-9dc3-ca9e0eeb76b5.png)

**Comment by notwaldorf** [comment]
You can't download the checkpoint just from going to that URL. You can either create a model that uses it:
```
const model = new mm.OnsetsAndFrames('https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni');
```
or using the [checkpoint_downloader.py](https://github.com/tensorflow/magenta-js/blob/master/scripts/checkpoint_downloader.py) script

**Comment by ismazmerli** [comment]
Hi Thanks for your help ! I managed to download the checkpoint ! 
But it doesn't seem to work when I want to run locally in a js script :
const model = new mm.OnsetsAndFrames("path/to/chekpoints");

Here are the chekpoint downloaded in a local folder.
![image](https://user-images.githubusercontent.com/45600611/73548677-7d103a80-4441-11ea-96c5-ea0f28fad8c7.png)

**Comment by adarob** [comment]
The script should have also downloaded 2 additional files which are missing in your directory listing: `weights_manifest.json` and `config.json`.
