### ISSUE TITLE
How to use magenta-js with my own checkpoint or a downloaded one ?

### ISSUE THREAD

**Issue by gelampr** [tensorflow/magenta-js#401]
I converted my own .mag file and got a folder containing a weights_manifest .json and .bin files .

I also downloaded a pretrained checkpoint and got the same type of files plus a config.json .

Is it possible to change the link inside the javascript part of an html file, lets say : 

const musicvae = new mm.MusicVAE("https://storage.googleapis.com/" +
            "magentadata/js/checkpoints/music_vae/trio_4bar");

in order to use my local files in the browser ? Is it supposed to place the folder path containing those local files instead of ("https://storage... ...trio4bar");

I tried it on XAMPP with  ("localhost/folder") but with no luck. Am I missing something ?

**Answer**: OK, it worked :)  I pointed that folder as:
const musicvae = new mm.MusicVAE('https://127.0.0.1/MUSIC/site01/trio4bar');

**Comment by gelampr** [comment]
OK, it worked :) Pointed that folder as:
const musicvae = new mm.MusicVAE('https://127.0.0.1/MUSIC/site01/trio4bar');

**Comment by notwaldorf** [comment]
Yup, that's exactly what you need to do! Glad you sorted it out!
