### ISSUE TITLE
Deal with tone.js deprecations.

### ISSUE THREAD

**Issue by adarob** [tensorflow/magenta-js#49]
music_vae_bundle.js:23113 [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.
music_vae_bundle.js:23118 [Deprecation] BiquadFilterNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
music_vae_bundle.js:23113 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by teropa** [comment]
These are Tone.js-internal (non-)issues, Chrome warning about dezippering removal with apparently nothing to be done Tonejs/Tone.js#288, Tonejs/Tone.js#282
