### ISSUE TITLE
Missing all checkpoint files

### ISSUE THREAD

**Issue by shlomotannor** [tensorflow/magenta-js#699]
I couldn't access any of the URLs that appear here:

https://github.com/magenta/magenta-js/blob/master/music/checkpoints/checkpoints.json

**Comment by iplanwebsites** [comment]
Where did they go? Are these hosted anywhere else?

**Comment by adarob** [comment]
You can't view the directory, but the files are there. The library knows how to read them. For example: https://storage.googleapis.com/magentadata/js/checkpoints/music_vae/drums_2bar_hikl_small/config.json
