### ISSUE TITLE
Two broken links in music/README.md

### ISSUE THREAD

**Issue by theangellmethod** [tensorflow/magenta-js#74]
The MusicRNN and (2) MusicVAE links are 404.

MusicRNN link:
https://github.com/tensorflow/magenta-js/blob/master/music/music_rnn

MusicVAE links:
https://github.com/tensorflow/magenta-js/blob/master/music/music_vae
https://g.co/musicvae

**Comment by adarob** [comment]
Fixed. Thanks!
